{{- if .Values.prom2teams.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "prom2teams-config-{{ include "pharos.name" $ }}"
  namespace: {{ include "pharos.namespace" $ | quote }}
data:
  teams.j2: |
    {
      "type": "message",
      "attachments": [
        {
          "contentType": "application/vnd.microsoft.card.adaptive",
          "content": {
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "type": "AdaptiveCard",
            "version": "1.4",
            "msteams": {
              "width": "Full"
            },
            "body": [
              {
                "type": "ColumnSet",
                "style": "{% if status=='resolved' %}good{% else %}attention{% endif %}",
                "columns": [
                  {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                      {
                        "type": "TextBlock",
                        "text": "Prometheus alert {{ "{{" }} msg_text.name {{ "}}" }} {% if status=='resolved' %}(Resolved){% elif status=='unknown' %}(status unknown){% else %}triggered{% endif %}",
                        "weight": "Bolder",
                        "size": "Large"
                      },
                      {
                        "type": "TextBlock",
                        "text": "{% if status=='resolved' %}(Resolved) {% endif %}{{ "{{" }} msg_text.summary {{ "}}" }}",
                        "wrap": true
                      }
                    ]
                  }
                ]
              },
              {
                "type": "FactSet",
                "facts": [
                  {% if msg_text.instance %} { "title": "Instance", "value": "{{ "{{" }} msg_text.instance {{ "}}" }}" }, {% endif %}
                  {% if msg_text.description %} { "title": "Description", "value": "{{ "{{" }} msg_text.description {{ "}}" }}" }, {% endif %}
                  { "title": "Status", "value": "{{ "{{" }} msg_text.status {{ "}}" }}" }
                ]
              }
            ],
            "actions": [
              {
                "type": "Action.OpenUrl",
                "title": "View details",
                "url": "{{ "{{" }} msg_text.generatorURL {{ "}}" }}"
              }
            ]
          }
        }
      ]
    }

{{ end }}