{{ if .Values.alertmanager.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "alertmanager-httproute-{{ include "pharos.name" $ }}"
  namespace: {{ include "pharos.namespace" $ | quote }}
spec:
  parentRefs:
  - name: gateway-{{ include "pharos.name" $ }}
    namespace: {{ include "pharos.namespace" $ | quote }}
    sectionName: https
  hostnames:
  - {{ .Values.alertmanager.httproute.hostname | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: alertmanager-svc-{{ include "pharos.name" $ }}
      port: {{ .Values.alertmanager.service.port }}

{{ end }}