namespace: pharos-testnet
nameOverride: ""
namespaceOverride: ""

network:
  type: testnet

image:
  repository: public.ecr.aws/k2g7b7g1/pharos/testnet
  tag: "rpc_community_0629"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "8"
    memory: "16Gi"
  limits:
    cpu: "16"
    memory: "32Gi"

persistence:
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 2000Gi

snapshot:
  url: "https://snapshot.dplabs-internal.com/testnet/snapshot-2025-05-27-03-13.tar.gz"
  dataDir: "/data/pharos-node/domain/light/data/public"
  enabled: false

customLabels: {}