{{ if .Values.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certmanager.certificate.name | default "domain-cert" }}
  namespace: {{ include "pharos.namespace" $ | quote }}
spec:
  secretName: {{ .Values.certmanager.certificate.secretName | default "domain-cert" }}
  dnsNames:
  {{- range .Values.certmanager.certificate.dnsNames }}
  - {{ . | quote }}
  {{- end }}
  issuerRef:
    name: {{ .Values.certmanager.clusterIssuer.name | default "letsencrypt" }}
    kind: ClusterIssuer
{{ end }}