{{- if .Values.prom2teams.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "prom2teams-secrets-{{ include "pharos.name" . }}"
  namespace: {{ include "pharos.namespace" . | quote }}
type: Opaque
stringData:
  config.ini: |
    [HTTP Server]
    Host: {{ .Values.prom2teams.http.host }}
    Port: {{ .Values.prom2teams.http.port }}

    [Microsoft Teams]
    {{- range .Values.prom2teams.connectors }}
    {{ .name }}: {{ .url }}
    {{- end }}

    [Template]
    Path: {{ .Values.prom2teams.templatePath }}

    [Log]
    Level: {{ .Values.prom2teams.logLevel }}
{{- end }}
