{{ if .Values.prometheus.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: "prometheus-httproute-{{ include "pharos.name" $ }}"
  namespace: {{ include "pharos.namespace" $ | quote }}
spec:
  parentRefs:
  - name: gateway-{{ include "pharos.name" $ }}  
    namespace: {{ include "pharos.namespace" $ | quote }}
    sectionName: https
  hostnames:
  - {{ .Values.prometheus.httproute.hostname | quote }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: prometheus-svc-{{ include "pharos.name" $ }}
      port: {{ .Values.prometheus.service.port }}
{{ end}}
