{{ if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "grafana-secrets-{{ include "pharos.name" $ }}"
  namespace: {{ include "pharos.namespace" $ | quote }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.grafana.adminUser | default "admin" }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | default "admin" }}
{{ end }}