{{ if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gateway.className }}
spec:
  controllerName: {{ default "gateway.envoyproxy.io/gatewayclass-controller" .Values.gateway.controllerName }}
{{ end }}