apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pharos.testnet.name" $ | lower }}
  namespace: {{ include "pharos.testnet.namespace" $ | quote }}
spec:
  serviceName: "{{ include "pharos.testnet.name" $ | lower }}"
  replicas: 1
  selector:
    matchLabels: {{- include "pharos.testnet.labels.standard" ( dict "customLabels" .Values.customLabels "context" $ ) | nindent 8 }}
  template:
    metadata:
      labels: 
      {{- include "pharos.testnet.labels.standard" ( dict "customLabels" .Values.customLabels "context" $ ) | nindent 8 }}
    spec:
      containers:
      - name: pharos
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 18100
          name: rpc
        - containerPort: 18200
          name: p2p
        - containerPort: 19000
          name: internal-service
        volumeMounts:
        - name: pharos-data
          mountPath: /data
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
  volumeClaimTemplates:
    - metadata:
        name: pharos-data
      spec:
        storageClassName: {{ default "default" .Values.persistence.storageClass }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}