{{ if .Values.grafana.enabled }}
{{- $defaultURL := printf "http://prometheus-svc-%s:%d" (include "pharos.name" $) (int .Values.prometheus.service.port) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "grafana-config-{{ include "pharos.name" $ }}"
  namespace: {{ include "pharos.namespace" $ | quote }}
data:
  datasources.yaml: |
    ---
    apiVersion: 1

    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: {{ default $defaultURL .Values.grafana.datasources.prometheus.url }}
        editable: true
        isDefault: true

  dashboard.yaml: |
    ---
    apiVersion: 1

    providers:
      - name: 'Pharos node dashboards'
        orgId: 1
        folder: 'Pharos Dashboards'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /etc/grafana/provisioning/dashboards/pharos
{{ end }}

