{{ if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "grafana-secrets-{{ include "pharos.name" $ }}"
  namespace: {{ include "pharos.namespace" $ | quote }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ default "admin" .Values.grafana.adminUser | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ default "admin" .Values.grafana.adminPassword | quote }}
{{ end }}