{{ if .Values.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "alertmanager-svc-{{ include "pharos.name" $ }}"
  namespace: {{ include "pharos.namespace" $ | quote }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.alertmanager.service.port }}
      targetPort: {{ .Values.alertmanager.service.port }}
  selector:
    {{- include "pharos.labels.standard" ( dict "customLabels" $.Values.alertmanager.customLabels "context" $ ) | nindent 9 }}

{{ end }}